### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by NIR-Ginko** [Krzysztow/modbus-utils#7]
There is no licensing information present in the repository or source code. Is it GPLv3-licensed as undelying `libmodbus` or has other license?

I want to package `modbus-utils` for ALT Linux but I can't do it unless the license is known.

**Comment by NIR-Ginko** [comment]
Ping @Krzysztow .

**Comment by Krzysztow** [comment]
Hello, sorry for slow response. I don't mind anything. Have done that a long time ago. If you think I need to add some license (and maybe have some idea, which is the least restrictive, I'll do). If this comment is enough, fine too ;)

**Comment by NIR-Ginko** [comment]
Hi! Here is out licensing suggestion: #8 . I suppose that MIT license is permissive enough and libmodbus is licensed under LGPL-2.1 which is compatible with MIT (AFAIK). The only moment under the question is `threaded-test-server.c` which is GPLv3+ licensed but I don't expect any problems since it is a separate from other sources.
